<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMlCcex\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMlCcex/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAMlCcex.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAMlCcex\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAMlCcex\App_KernelProdContainer([
    'container.build_hash' => 'AMlCcex',
    'container.build_id' => 'e82dcf62',
    'container.build_time' => 1671715539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMlCcex');
