<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_articles' => [[], ['_controller' => 'App\\Controller\\ArticleController::lesArticles'], [], [['text', '/articles']], [], [], []],
    'app_fiche_article' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::unArticle'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/article']], [], [], []],
    'app_article_ajout' => [[], ['_controller' => 'App\\Controller\\ArticleController::ajout'], [], [['text', '/admin/article_ajout']], [], [], []],
    'app_article_modifier' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::modifier'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/article_modifier']], [], [], []],
    'app_article_supprimer' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::supprimer'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/article_supprimer']], [], [], []],
    'app_auteur_ajout' => [[], ['_controller' => 'App\\Controller\\AuteurController::ajout'], [], [['text', '/auteur_ajout']], [], [], []],
    'app_auteurs' => [[], ['_controller' => 'App\\Controller\\AuteurController::lesAuteurs'], [], [['text', '/auteurs']], [], [], []],
    'app_auteur' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::unAuteur'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/auteur']], [], [], []],
    'app_auteur_update' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::update'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/auteur_update']], [], [], []],
    'app_auteur_delete' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::delete'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/auteur_delete']], [], [], []],
    'app_categorie_ajout' => [[], ['_controller' => 'App\\Controller\\CategorieController::ajout'], [], [['text', '/categorie']], [], [], []],
    'app_categorie_update' => [['slug'], ['_controller' => 'App\\Controller\\CategorieController::modifier'], [], [['variable', '', '[^/]++', 'slug', true], ['text', '/categorie_update']], [], [], []],
    'app_categorie_article' => [['slug'], ['_controller' => 'App\\Controller\\CategorieController::articlesCategorie'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/categorie_']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_passer_en_admin' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::passerEnAdmin'], ['id' => '\\d+'], [['variable', '_', '\\d+', 'id', true], ['text', '/passer-en-admin']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
    'cgv' => [[], ['template' => 'statique/cgv.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/cgv']], [], [], []],
    'contact' => [[], ['template' => 'statique/contact.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/contact']], [], [], []],
    'devenir_blogueur' => [[], ['template' => 'statique/devenirBlogueur.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/devenirBlogueur']], [], [], []],
    'join_team' => [[], ['template' => 'statique/joinTeam.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/joinTeam']], [], [], []],
    'qui_sommes_nous' => [[], ['template' => 'statique/quiSommesNous.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/quiSommesNous']], [], [], []],
    'values' => [[], ['template' => 'statique/values.html.twig', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController'], [], [['text', '/values']], [], [], []],
];
