<?php

namespace ContainerLHWWKIk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_68ge2b8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.68ge2b8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.68ge2b8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenGenerator' => ['privates', '.errored.AQoqzEw', NULL, 'Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $tokenGenerator argument is type-hinted with the non-existent class or interface: "App\\Controller\\TokenGeneratorInterFace". Did you forget to add a use statement?'],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManager' => '?',
            'tokenGenerator' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
