<?php

namespace ContainerLHWWKIk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_AQoqzEwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.AQoqzEw' shared service.
     *
     * @return \App\Controller\TokenGeneratorInterFace
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $tokenGenerator argument is type-hinted with the non-existent class or interface: "App\\Controller\\TokenGeneratorInterFace". Did you forget to add a use statement?');
    }
}
