<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQI9mUhQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQI9mUhQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQI9mUhQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQI9mUhQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQI9mUhQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QI9mUhQ',
    'container.build_id' => '9089c733',
    'container.build_time' => 1671723482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQI9mUhQ');
